{% set name = "vmd-python" %}
{% set version = "3.1.5" %}
{% set sha256 = "f6c225dade86324000467938252cc65b0227c4ec789c2e0b91e6bea739ef4827" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-v{{ version }}.tar.gz
  url: https://github.com/Eigenstate/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - perl
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - make
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - setuptools
    - swig
    - numpy
  host:
    - python
    - pip
    - libnetcdf
    - expat
    - numpy
    - tk
    - setuptools
    - sqlite

  run:
    - python
    - libnetcdf
    - expat
    - {{ pin_compatible('numpy') }}
    - tk
    - sqlite

test:
  requires:
    - pytest
  commands:
    - py.test --pyargs vmd

about:
  home: http://github.com/Eigenstate/vmd-python
  license: VMD
  license_file: LICENSE
  summary: "Visual Molecular Dynamics (VMD) Python bindings"
  description: |
    vmd-python is Visual Molecular Dynamics (VMD) built as a Python extension
    module, with a few usability improvements. It includes functionality for
    loading and manipulating a variety of molecule file formats, working
    with trajectories, and many assorted plugins.
  doc_url: http://vmd.robinbetz.com
  dev_url: https://github.com/Eigenstate/vmd-python

extra:
  recipe-maintainers:
    - Eigenstate
