{% set name = "vmd-python" %}
{% set version = "3.1.0" %}
{% set sha256 = "b155b76d40ff9198b6c9fb426cf56158eb6d663419e9cda96fea8947eb751b3b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-v{{ version }}.tar.gz
  url: https://github.com/Eigenstate/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - perl
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - libnetcdf
    - expat
    - numpy
    - tk
    - sqlite

  run:
    - python
    - libnetcdf
    - expat
    - {{ pin_compatible('numpy') }}
    - tk
    - sqlite

test:
  requires:
    - pytest
  commands:
    - py.test --pyargs vmd
    - conda inspect linkages -p $PREFIX {{ name|lower }}  # [not win]
    - conda inspect objects -p $PREFIX {{ name|lower }}  # [osx]

about:
  home: http://github.com/Eigenstate/vmd-python
  license: VMD
  license_file: LICENSE
  summary: "Visual Molecular Dynamics (VMD) Python bindings"
  description: |
    vmd-python is Visual Molecular Dynamics (VMD) built as a Python extension
    module, with a few usability improvements. It includes functionality for
    loading and manipulating a variety of molecule file formats, working
    with trajectories, and many assorted plugins.
  doc_url: http://vmd.robinbetz.com
  dev_url: https://github.com/Eigenstate/vmd-python

extra:
  recipe-maintainers:
    - Eigenstate
